# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170322_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='myimage',
            field=models.ImageField(blank=True, upload_to='upload/%Y/%m/%d'),
        ),
    ]
