# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170312_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='Receive_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='Take_time',
            field=models.DateTimeField(null=True),
        ),
    ]
