# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 09:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170312_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='Take_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
